import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

const __dirname = fileURLToPath(new URL(".", import.meta.url)).replace(
  /\/+$/,
  "",
);

const { version } = JSON.parse(
  await readFile(`${__dirname}/../package.json`, "utf8"),
) as { version: string };

await writeFile(
  `${__dirname}/../src/version.ts`,
  `\
// This file is autogenerated by /scripts/version.mts
export const version = ${JSON.stringify(version)};
`,
);
